/**
 * Studio ▸ Listening: the saved headphone calibration, and everything a
 * session can play to set it against.
 *
 * The Mac's argument is that a balance cannot be set one part at a time —
 * what matters most is *speech against room*, and the room is never the only
 * thing playing. So all four sources are here and all reachable while the bed
 * is running: the bed itself on `auditionPlan` (one mid-band stage with every
 * texture present, so no texture slider is inert), the resonant tuning and
 * the return signal cued into that same running plan, and the voice, spoken
 * on demand by the engine rather than played from a file.
 *
 * The tuning and the return signal are generated by the bed, so auditioning
 * them is a matter of asking the engine for them at its own clock — the same
 * path a session plays them on. A level balanced against a different path
 * would be balanced against a fiction.
 */
import { $ } from "./dom.js";
import type { BedPlayer } from "./bed.js";
import type { AudioProfile } from "../core/audioProfile.js";
import type { BedPlan } from "../core/bedPlan.js";

interface LevelRow { name: string; field: keyof AudioProfile; tint: string; why: string }
type ListeningReply =
  | { ok: true; profile: AudioProfile; bed: BedPlan; levels: LevelRow[] }
  | { ok: false; error: string };

/** The Mac autosaves 600 ms after the last drag, for the reason a port has
 *  too: a slider emits a value per frame, and each one is a file write. */
const saveDelay = 600;

/** Long enough to get past the fade and hear it at full, which is what a
 *  level check needs — the Mac's calibration uses ten seconds for the same
 *  reason. The tuning gets longer because it moves through vowels. */
const returnSeconds = 10;
const tuningSeconds = 14;

export class ListeningPane {
  private profile: AudioProfile | undefined;
  private bedPlan: BedPlan | undefined;
  private saveTimer: ReturnType<typeof setTimeout> | undefined;
  private loaded = false;

  constructor(private readonly bed: BedPlayer) {}

  /** Loaded on first visit, not at launch: it reads a file, and most sessions
   *  never open this pane. */
  async open(): Promise<void> {
    if (!this.loaded) {
      const reply: ListeningReply = await window.gateway.listening();
      if (!reply.ok) {
        $("mixError").textContent = `The calibration did not load: ${reply.error}`;
        $("mixError").hidden = false;
        return;
      }
      this.profile = reply.profile;
      this.bedPlan = reply.bed;
      this.render(reply.levels);
      this.loaded = true;
    }
    this.setTransport(false);
  }

  /** Leaving the pane. The bed is stopped by the caller; this makes sure the
   *  last drag reaches the file rather than being lost to the navigation. */
  close(): void { this.flush(); }

  private render(levels: LevelRow[]): void {
    const mixer = $("mixer");
    mixer.textContent = "";
    for (const level of levels) {
      mixer.append(this.row(level));
    }
  }

  private row(level: LevelRow): HTMLElement {
    const wrap = document.createElement("div");
    wrap.className = "mixrow";

    const name = document.createElement("label");
    name.className = "mixname";
    name.textContent = level.name;
    name.htmlFor = `mix-${level.field}`;

    const input = document.createElement("input");
    input.type = "range";
    input.id = `mix-${level.field}`;
    input.min = "0";
    input.max = "1";
    input.step = "0.01";
    input.value = String(this.profile?.[level.field] ?? 0);
    input.style.accentColor = `var(--${level.tint})`;

    const value = document.createElement("span");
    value.className = "mixvalue";
    const paint = () => {
      const v = Number(input.value);
      value.textContent = `${Math.round(v * 100)}%`;
      value.style.color = v === 0 ? "var(--comment)" : `var(--${level.tint})`;
    };
    paint();

    input.addEventListener("input", () => {
      if (!this.profile) return;
      this.profile = { ...this.profile, [level.field]: Number(input.value) };
      paint();
      // Straight to the audio thread, where it ramps. The point of a slider
      // is that it is audible while it moves, not on the next run.
      this.bed.recalibrate(this.profile);
      this.scheduleSave();
    });

    const why = document.createElement("p");
    why.className = "mixwhy";
    why.textContent = level.why;

    const head = document.createElement("div");
    head.className = "mixhead";
    head.append(name, input, value);
    wrap.append(head, why);
    return wrap;
  }

  // ------------------------------------------------------------- transport

  private setTransport(sounding: boolean): void {
    $("mixListenLabel").textContent = sounding ? "Stop" : "Start listening";
    $("mixListenGlyph").textContent = sounding ? "\u25a0" : "\u25b6";
    $("mixTransport").classList.toggle("is-sounding", sounding);
    ($("mixTuning") as HTMLButtonElement).disabled = !sounding;
    ($("mixReturn") as HTMLButtonElement).disabled = !sounding;
    ($("mixSpeak") as HTMLButtonElement).disabled = !sounding || this.speaking;
    $("mixSounding").textContent = sounding
      ? "the bed alone — one mid-band stage with every texture present"
      : "nothing playing";
  }

  async toggle(): Promise<void> {
    if (this.bed.isSounding) { this.bed.stop(); return; }
    if (!this.bedPlan || !this.profile) return;
    await this.bed.play(this.bedPlan, this.profile);
  }

  /** The engine loads on the first line asked for, which takes a moment the
   *  first time and no time after. Said, rather than shown as a button that
   *  appears not to have worked. */
  private speaking = false;
  private narration: { samples: Float32Array<ArrayBuffer>; sampleRate: number } | undefined;

  async speak(): Promise<void> {
    if (!this.bed.isSounding || this.speaking || !this.profile) return;
    this.speaking = true;
    const button = $("mixSpeak") as HTMLButtonElement;
    button.disabled = true;
    try {
      if (!this.narration) {
        $("mixSounding").textContent = "loading the voice";
        const reply = await window.gateway.speakCalibration();
        if (!reply.ok) {
          $("mixError").textContent = `The voice did not speak: ${reply.error}`;
          $("mixError").hidden = false;
          return;
        }
        this.narration = { samples: new Float32Array(reply.samples), sampleRate: reply.sampleRate };
        $("mixSpeakLine").textContent = `“${reply.text}” — ${reply.voice}`;
        $("mixSpeakLine").hidden = false;
      }
      const seconds = this.narration.samples.length / this.narration.sampleRate;
      this.bed.speak(this.narration.samples, this.narration.sampleRate, this.profile.speech);
      $("mixSounding").textContent = "the bed · narration";
      await new Promise(r => setTimeout(r, seconds * 1000));
    } finally {
      this.speaking = false;
      if (this.bed.isSounding) this.setTransport(true);
    }
  }

  cue(what: "tuning" | "return"): void {
    if (!this.bed.isSounding) return;
    this.bed.cue(what, what === "return" ? returnSeconds : tuningSeconds);
    $("mixSounding").textContent = what === "return"
      ? "the bed · return signal"
      : "the bed · resonant tuning";
    setTimeout(() => {
      if (this.bed.isSounding) this.setTransport(true);
    }, (what === "return" ? returnSeconds : tuningSeconds) * 1000);
  }

  /** Called by the page's own bed-state listener, so the transport follows
   *  the ramp rather than the click. */
  bedState(sounding: boolean): void {
    if (!$("paneListening").hidden) this.setTransport(sounding);
  }

  // ------------------------------------------------------------------ save

  private scheduleSave(): void {
    if (this.saveTimer !== undefined) clearTimeout(this.saveTimer);
    this.saveTimer = setTimeout(() => { void this.save(); }, saveDelay);
  }

  private flush(): void {
    if (this.saveTimer === undefined) return;
    clearTimeout(this.saveTimer);
    this.saveTimer = undefined;
    void this.save();
  }

  private async save(): Promise<void> {
    this.saveTimer = undefined;
    if (!this.profile) return;
    const reply = await window.gateway.saveListening(this.profile);
    const error = $("mixError");
    // Being unable to save is the only failure here worth a colour: the
    // levels will not survive a relaunch, and nothing on screen would say so.
    error.hidden = reply.ok;
    error.textContent = reply.ok ? "" : `These levels are not being saved: ${reply.error}`;
  }
}
