/**
 * What an assembled session is, ported from `SessionManifest.swift`.
 *
 * Every field decodes with a default, deliberately: a manifest written before a
 * field existed still has to load, because the audio beside it is still
 * playable. Nothing here throws on a missing key.
 */
import { type BedPlan, buildPlan, makeTuning, makeWarble, tuningForm, type TimelineEntry } from "./bedPlan.js";
import type { Level, SignalProfile } from "./level.js";

export type AudioAssetRole = "resonantTuning" | "returnSignal";
export type AudioAssetFit = "once" | "cropOrLoop";
export type SessionPurpose = "standard" | "continuousJourney";

/** A placement, not a file: both sounds are generated by the bed now, and what
 *  the manifest decides is where they sit and how long they run. The `asset`
 *  and `file` fields survive on old manifests and are ignored. */
export interface MediaCue {
  role: AudioAssetRole;
  asset: string;
  file: string;
  startSeconds: number;
  seconds: number;
  fit: AudioAssetFit;
  crossfadeSeconds: number;
  edgeFadeSeconds: number;
  gain: number;
}

export interface Entry {
  segment: string;
  file: string;
  seed: bigint;
  startSeconds?: number;
  seconds?: number;
  /** The take's render stamp when it was laid into this track. **Nil means
   *  unknown, never current** — a manifest written before this field existed
   *  cannot prove anything about its own audio. */
  stamp?: string;
}

export interface Cue {
  seconds: number;
  /** "level", "surf" or "bed". */
  kind: string;
  text: string;
  args: number[];
  /** The segment this cue came from, or absent for a template-level cue. */
  source?: string;
}

export interface SessionExit {
  segment: string; title: string; sourceFile: string; outputName: string;
}

export interface SessionManifest {
  template: string;
  verbosity: number;
  voice: string;
  seconds: number;
  narrationOnly: boolean;
  level?: string;
  startLevel?: string;
  ending?: string;
  purpose: SessionPurpose;
  exit?: SessionExit;
  segments: Entry[];
  cues: Cue[];
  media: MediaCue[];
}

// ------------------------------------------------------------------ decode

const str = (v: unknown, fallback: string): string => (typeof v === "string" ? v : fallback);
const num = (v: unknown, fallback: number): number => (typeof v === "number" ? v : fallback);
const bool = (v: unknown, fallback: boolean): boolean => (typeof v === "boolean" ? v : fallback);
const optStr = (v: unknown): string | undefined => (typeof v === "string" ? v : undefined);
const optNum = (v: unknown): number | undefined => (typeof v === "number" ? v : undefined);

export const entryEndSeconds = (e: Entry): number | undefined =>
  e.startSeconds !== undefined && e.seconds !== undefined ? e.startSeconds + e.seconds : undefined;

function decodeEntry(raw: Record<string, unknown>): Entry {
  const start = optNum(raw.startSeconds), secs = optNum(raw.seconds), stamp = optStr(raw.stamp);
  return {
    segment: str(raw.segment, "untitled"),
    file: str(raw.file, ""),
    // UInt64 in Swift. JSON numbers past 2^53 would already have lost
    // precision on the way in, so this reads whatever survived rather than
    // pretending otherwise.
    seed: typeof raw.seed === "number" ? BigInt(Math.trunc(raw.seed)) : 0n,
    ...(start !== undefined ? { startSeconds: start } : {}),
    ...(secs !== undefined ? { seconds: secs } : {}),
    ...(stamp !== undefined ? { stamp } : {}),
  };
}

function decodeCue(raw: Record<string, unknown>): Cue {
  const source = optStr(raw.source);
  return {
    seconds: num(raw.seconds, 0),
    kind: str(raw.kind, ""),
    text: str(raw.text, ""),
    args: Array.isArray(raw.args) ? (raw.args as number[]) : [],
    ...(source !== undefined ? { source } : {}),
  };
}

function decodeMedia(raw: Record<string, unknown>): MediaCue {
  return {
    role: raw.role === "returnSignal" ? "returnSignal" : "resonantTuning",
    asset: str(raw.asset, ""),
    file: str(raw.file, ""),
    startSeconds: num(raw.startSeconds, 0),
    seconds: num(raw.seconds, 0),
    fit: raw.fit === "cropOrLoop" ? "cropOrLoop" : "once",
    crossfadeSeconds: num(raw.crossfadeSeconds, 0),
    edgeFadeSeconds: num(raw.edgeFadeSeconds, 1),
    gain: num(raw.gain, 1),
  };
}

/**
 * **An unrecognised purpose makes the whole manifest unreadable.**
 *
 * Swift decodes `SessionPurpose` as a `String` enum, and an unknown raw value
 * throws rather than falling back — so `SessionManifestIO.load` returns nil and
 * the app treats the session as having no manifest at all. A port that quietly
 * read it as `.standard` would play a session the Mac calls corrupt, which is
 * the worst kind of divergence: not a crash, a disagreement about reality.
 *
 * Found because the fixture recorded which constructed cases Swift *refused*,
 * rather than skipping them.
 */
function decodePurpose(v: unknown): SessionPurpose {
  if (v === undefined || v === null) return "standard";
  if (v === "standard" || v === "continuousJourney") return v;
  throw new Error(`unknown SessionPurpose "${String(v)}"`);
}

export function decodeManifest(rawIn: unknown): SessionManifest {
  const raw = (rawIn ?? {}) as Record<string, unknown>;
  const segments = Array.isArray(raw.segments)
    ? (raw.segments as Record<string, unknown>[]).map(decodeEntry) : [];
  const level = optStr(raw.level), startLevel = optStr(raw.startLevel), ending = optStr(raw.ending);
  const exitRaw = raw.exit as Record<string, unknown> | undefined;
  const exit = exitRaw && typeof exitRaw === "object" ? {
    segment: str(exitRaw.segment, ""), title: str(exitRaw.title, ""),
    sourceFile: str(exitRaw.sourceFile, ""), outputName: str(exitRaw.outputName, ""),
  } : undefined;

  // A manifest that lost its own length can still be measured from its pieces;
  // the audio file is the final authority either way.
  const ends = segments.map(entryEndSeconds).filter((v): v is number => v !== undefined);
  const seconds = optNum(raw.seconds) ?? (ends.length > 0 ? Math.max(...ends) : 0);

  return {
    template: str(raw.template, "untitled"),
    verbosity: num(raw.verbosity, 3),
    voice: str(raw.voice, "M1"),
    seconds,
    narrationOnly: bool(raw.narrationOnly, true),
    ...(level !== undefined ? { level } : {}),
    ...(startLevel !== undefined ? { startLevel } : {}),
    ...(ending !== undefined ? { ending } : {}),
    purpose: decodePurpose(raw.purpose),
    ...(exit !== undefined ? { exit } : {}),
    segments,
    cues: Array.isArray(raw.cues) ? (raw.cues as Record<string, unknown>[]).map(decodeCue) : [],
    media: Array.isArray(raw.media) ? (raw.media as Record<string, unknown>[]).map(decodeMedia) : [],
  };
}

// ----------------------------------------------------------------- lookups

/** Whether the entries carry timings at all. A timeline must say when they do
 *  not, rather than silently draw every piece starting at zero. */
export const hasTimings = (m: SessionManifest): boolean =>
  m.segments.some(e => e.startSeconds !== undefined);

/** The piece sounding at a moment. Undefined before the first timed entry, in
 *  the silences between pieces, and always when there are no timings.
 *
 *  Takes the *last* match, not the first — overlapping entries resolve to the
 *  most recently started, which is what the Swift loop does by assigning
 *  without breaking. */
export function entryAt(m: SessionManifest, t: number): Entry | undefined {
  let current: Entry | undefined;
  for (const e of m.segments) {
    if (e.startSeconds === undefined || e.startSeconds > t) continue;
    const end = entryEndSeconds(e);
    if (end !== undefined && t >= end) continue;
    current = e;
  }
  return current;
}

export function indexAt(m: SessionManifest, t: number): number | undefined {
  let current: number | undefined;
  m.segments.forEach((e, i) => {
    if (e.startSeconds === undefined || e.startSeconds > t) return;
    const end = entryEndSeconds(e);
    if (end !== undefined && t >= end) return;
    current = i;
  });
  return current;
}

/** The bed for this tape. Undefined when the manifest predates cue recording —
 *  a tape assembled before the bed existed has no timeline to run one on, and
 *  inventing one would put transitions in the wrong places. */
export function bedPlan(
  m: SessionManifest, levels: Level[], signals: SignalProfile[] = [],
): BedPlan | undefined {
  if (m.cues.length === 0 || m.seconds <= 0) return undefined;
  const timeline: TimelineEntry[] = [...m.cues]
    // Swift's `sorted(by:)` is stable, so equal timestamps keep their order.
    .map((c, i) => ({ c, i }))
    .sort((a, b) => (a.c.seconds - b.c.seconds) || (a.i - b.i))
    .map(({ c }) => ({ seconds: c.seconds, kind: c.kind, text: c.text, args: c.args }));

  const plan = buildPlan({
    timeline, levels, signals,
    startLevel: m.startLevel ?? "F10",
    totalSeconds: m.seconds,
    ending: m.ending ?? "return",
  });

  const destination = m.level ?? m.startLevel ?? "F10";
  const tuningCue = m.media.find(c => c.role === "resonantTuning");
  if (tuningCue && tuningCue.seconds > 0) {
    plan.tuning = makeTuning(tuningForm(destination), tuningCue.startSeconds, tuningCue.seconds);
  }
  const returnCue = m.media.find(c => c.role === "returnSignal");
  if (returnCue && returnCue.seconds > 0) {
    plan.warble = makeWarble(returnCue.startSeconds, returnCue.seconds);
  }
  return plan;
}

// ------------------------------------------------------------------ naming

const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];

/**
 * Swift's `String.capitalized`, which is not "upper the first character".
 *
 * It uppercases the first letter of every *word* and lowercases the rest, and
 * digits break words — so `0a1b2926` becomes `0A1B2926`, not `0a1b2926`. A
 * session directory ends in an eight-character hash, so this is visible on the
 * name of nearly every assembled session, and getting it wrong was invisible
 * against the real corpus because those names are compared as whole strings.
 */
export function capitalized(s: string): string {
  let out = "";
  let atWordStart = true;
  for (const ch of s) {
    const isLetter = /\p{L}/u.test(ch);
    out += isLetter && atWordStart ? ch.toUpperCase() : ch.toLowerCase();
    atWordStart = !isLetter;
  }
  return out;
}

/**
 * The `yyyy-MM-dd` a directory name opens with, rendered for reading.
 *
 * **A fixed English month table, not a locale.** Swift builds this with a
 * `DateFormatter` on the system locale, so on a French Mac it would say
 * "30 août 2026". The name is a file-listing label rather than prose, the
 * fixture pins the English form, and a port that followed the host locale would
 * disagree with Swift on any machine not set to English — including, silently,
 * on the tester's.
 */
export function dateIn(directory: string): string | undefined {
  const parts = directory.split("-");
  if (parts.length < 3 || parts[0]!.length !== 4) return undefined;
  const y = Number(parts[0]), m = Number(parts[1]), d = Number(parts[2]);
  if (!Number.isInteger(y) || !Number.isInteger(m) || !Number.isInteger(d)) return undefined;
  if (parts[1] === "" || parts[2] === "") return undefined;
  if (m < 1 || m > 12 || d < 1 || d > 31) return undefined;
  // **Swift rolls over rather than rejecting.** `Calendar.date(from:)` is
  // lenient by default, so 2026-02-31 is 3 March 2026, not nil. A port that
  // validated the date instead would drop the label from any directory whose
  // name carried an impossible day — rare, but silently and only there.
  // `Date.UTC` rolls over the same way, so the date is simply formatted.
  const date = new Date(Date.UTC(y, m - 1, d));
  return `${date.getUTCDate()} ${MONTHS[date.getUTCMonth()]} ${date.getUTCFullYear()}`;
}

/** The trailing eight-character hash, when there is one. */
export function hashIn(directory: string): string | undefined {
  const parts = directory.split("-");
  const last = parts[parts.length - 1];
  if (!last || last.length !== 8) return undefined;
  return /^[0-9a-fA-F]{8}$/.test(last) ? last : undefined;
}

/** What the session is *about*, with the level taken out of it: the level is
 *  already the first thing shown, so "F27 · Continuous F27" says nothing twice. */
export function subject(template: string, level?: string): string {
  let slug = template;
  if (slug.startsWith("continuous-")) return "Continuous journey";
  if (level && slug.toLowerCase().startsWith(level.toLowerCase() + "-")) {
    slug = slug.slice(level.length + 1);
  }
  // A bare `f27-visit` with no manifest level still should not read "F27".
  if (/^f[0-9]+-/.test(slug)) {
    const dash = slug.indexOf("-");
    slug = dash >= 0 ? slug.slice(dash + 1) : "";
  }
  if (slug === "") return "";
  return slug.split("-").filter(p => p !== "").map(capitalized).join(" ");
}

/** `F27 · The Park · 30 Aug 2026 · 0a1b2926` */
export function displayName(
  directoryName: string, manifest?: SessionManifest, title?: string,
): string {
  const parts: string[] = [];
  if (manifest?.level && manifest.level !== "") parts.push(manifest.level);
  const topic = title ?? subject(manifest?.template ?? directoryName, manifest?.level);
  if (topic !== "") parts.push(topic);
  const date = dateIn(directoryName);
  if (date !== undefined) parts.push(date);
  const hash = hashIn(directoryName);
  if (hash !== undefined) parts.push(hash);
  return parts.join(" · ");
}

/** Failure to load is undefined, never a throw: a track whose manifest is
 *  missing or corrupt is still a track you can play. */
export function loadManifest(json: string): SessionManifest | undefined {
  try { return decodeManifest(JSON.parse(json)); } catch { return undefined; }
}

// ------------------------------------------------------------------ encode

/** Sort keys, the same rule `JSONEncoder.sortedKeys` applies — needed only by
 *  callers that write a manifest back to disk (SessionPlacement's repair,
 *  and the constructed round-trip cases in its parity check). */
function sortKeys(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(sortKeys);
  if (v !== null && typeof v === "object") {
    return Object.fromEntries(
      Object.keys(v as object).sort().map(k => [k, sortKeys((v as Record<string, unknown>)[k])]),
    );
  }
  return v;
}

const encodeEntry = (e: Entry): Record<string, unknown> => ({
  segment: e.segment, file: e.file, seed: Number(e.seed),
  ...(e.startSeconds !== undefined ? { startSeconds: e.startSeconds } : {}),
  ...(e.seconds !== undefined ? { seconds: e.seconds } : {}),
  ...(e.stamp !== undefined ? { stamp: e.stamp } : {}),
});

const encodeCue = (c: Cue): Record<string, unknown> => ({
  seconds: c.seconds, kind: c.kind, text: c.text, args: c.args,
  ...(c.source !== undefined ? { source: c.source } : {}),
});

const encodeMedia = (m: MediaCue): Record<string, unknown> => ({
  role: m.role, asset: m.asset, file: m.file,
  startSeconds: m.startSeconds, seconds: m.seconds, fit: m.fit,
  crossfadeSeconds: m.crossfadeSeconds, edgeFadeSeconds: m.edgeFadeSeconds, gain: m.gain,
});

/** The plain-object form Swift's synthesized `Encodable` would produce: every
 *  required field present, every absent optional omitted entirely — never
 *  written as `null`, which is a different JSON value from an absent key. */
export function encodeManifestObject(m: SessionManifest): Record<string, unknown> {
  return {
    template: m.template, verbosity: m.verbosity, voice: m.voice, seconds: m.seconds,
    narrationOnly: m.narrationOnly,
    ...(m.level !== undefined ? { level: m.level } : {}),
    ...(m.startLevel !== undefined ? { startLevel: m.startLevel } : {}),
    ...(m.ending !== undefined ? { ending: m.ending } : {}),
    purpose: m.purpose,
    ...(m.exit !== undefined ? { exit: m.exit } : {}),
    segments: m.segments.map(encodeEntry),
    cues: m.cues.map(encodeCue),
    media: m.media.map(encodeMedia),
  };
}

/** `.sortedKeys, .prettyPrinted` — two-space indent, keys alphabetical at
 *  every level, matching what `SessionManifestIO.save` writes. */
export const encodeManifest = (m: SessionManifest): string =>
  JSON.stringify(sortKeys(encodeManifestObject(m)), null, 2);
